agents:
  p:
    name: "Patricia the RFC Producer"
    role: "rfc_producer"
    description: "Specializes in refining ideas into well-structured RFC documents"
    tool_tags: ["rfc", "codebase_analysis", "web_research"]
    prompt_file: "agent_patricia.prompt.md"
    context_sources: ["rfc_templates", "existing_rfcs", "codebase_structure"]
    color: "#9C27B0"
    icon: "📝"
    tool_sets: ["rfc_management", "codebase_analysis", "web_research"]
    continuation_config:
      rules:
        - trigger_tools: ["list_rfcs"]
          keywords: ["create", "new", "add", "make", "generate", "write", "draft", "test"]
          continuation_message: "Now create the RFC as requested. Use any details mentioned in the conversation, or use reasonable defaults for title, author, and body."
        - trigger_tools: ["list_rfcs"]
          keywords: ["rfc for", "rfc about"]
          continuation_message: "Now create the RFC for the topic mentioned."
      default_message: "Continue with the RFC refinement process."
  
  a:
    name: "Alice the AI Assistant"
    role: "assistant" 
    description: "General-purpose AI assistant for coding and problem-solving"
    tool_tags: ["filesystem", "command", "analysis"]
    prompt_file: "alice_assistant.prompt.md"
    context_sources: ["conversation_history", "workspace_structure"]
    color: "#2196F3"
    icon: "🤖"
    
  t:
    name: "Tessa the Tester"
    role: "tester"
    description: "Generates comprehensive test suites and test plans"
    tool_tags: ["filesystem", "testing", "analysis"]
    prompt_file: "agent_tester.prompt.md"
    context_sources: ["existing_tests", "code_coverage", "test_patterns"]
    color: "#4CAF50"
    icon: "🧪"
    
  d:
    name: "Debbie the Debugger"
    role: "debugging_assistant"
    description: "Intelligent debugging companion for AIWhisperer development"
    tool_tags: ["debugging", "monitoring", "testing", "analysis", "filesystem", "command"]
    prompt_file: "debbie_debugger.prompt.md"
    context_sources: ["session_history", "error_logs", "performance_metrics", "workspace_structure"]
    color: "#FF5722"
    icon: "🐛"
    tool_sets: ["debugging_tools", "filesystem", "command", "analysis"]
    capabilities:
      - session_monitoring
      - error_detection
      - performance_analysis
      - automated_recovery
      - script_execution
    configuration:
      monitoring:
        continuation_timeout: 30  # seconds
        memory_threshold: 512    # MB
        response_time_alert: 10  # seconds
      intervention:
        auto_continue: true
        max_retries: 3
        recovery_strategies: ["prompt", "restart", "escalate"]
    continuation_config:
      rules:
        - trigger_tools: ["session_inspector", "log_analyzer"]
          keywords: ["stall", "stuck", "waiting", "timeout", "not responding"]
          continuation_message: "Based on the analysis, I'll now attempt to resolve the issue. Let me inject a continuation prompt to unstick the agent."
        - trigger_tools: ["python_executor"]
          keywords: ["analyze", "debug", "investigate", "examine"]
          continuation_message: "I've executed the debugging script. Let me analyze the results and provide recommendations."
      default_message: "Continue with the debugging investigation."