agents:
  p:
    name: "Patricia the RFC Producer"
    role: "rfc_producer"
    description: "Specializes in refining ideas into well-structured RFC documents"
    tool_tags: ["rfc", "codebase_analysis", "web_research"]
    prompt_file: "agent_patricia.prompt.md"
    context_sources: ["rfc_templates", "existing_rfcs", "codebase_structure"]
    color: "#9C27B0"
    icon: "📝"
    tool_sets: ["rfc_management", "codebase_analysis", "web_research"]
    continuation_config:
      rules:
        - trigger_tools: ["list_rfcs"]
          keywords: ["create", "new", "add", "make", "generate", "write", "draft", "test"]
          continuation_message: "Now create the RFC as requested. Use any details mentioned in the conversation, or use reasonable defaults for title, author, and body."
        - trigger_tools: ["list_rfcs"]
          keywords: ["rfc for", "rfc about"]
          continuation_message: "Now create the RFC for the topic mentioned."
      default_message: "Continue with the RFC refinement process."
  
  a:
    name: "Alice the AI Assistant"
    role: "assistant" 
    description: "General-purpose AI assistant for coding and problem-solving"
    tool_tags: ["filesystem", "command", "analysis"]
    prompt_file: "alice_assistant.prompt.md"
    context_sources: ["conversation_history", "workspace_structure"]
    color: "#2196F3"
    icon: "🤖"
    
  t:
    name: "Tessa the Tester"
    role: "tester"
    description: "Generates comprehensive test suites and test plans"
    tool_tags: ["filesystem", "testing", "analysis"]
    prompt_file: "agent_tester.prompt.md"
    context_sources: ["existing_tests", "code_coverage", "test_patterns"]
    color: "#4CAF50"
    icon: "🧪"
    
  d:
    name: "Debbie the Debugger"
    role: "debugging_assistant, batch_processor"
    description: "Intelligent debugging companion and batch script processor for AIWhisperer"
    tool_tags: ["debugging", "monitoring", "testing", "analysis", "filesystem", "command", "batch"]
    prompt_file: "debbie_debugger.prompt.md"
    context_sources: ["session_history", "error_logs", "performance_metrics", "workspace_structure", "batch_scripts"]
    color: "#FF5722"
    icon: "🐛"
    tool_sets: ["debugging_tools", "batch_tools", "monitoring_tools", "filesystem", "command", "analysis"]
    capabilities:
      - session_monitoring
      - error_detection
      - performance_analysis
      - automated_recovery
      - script_execution
      - batch_script_processing
      - multi_format_parsing
      - automated_user_simulation
    configuration:
      monitoring:
        continuation_timeout: 30  # seconds
        memory_threshold: 512    # MB
        response_time_alert: 10  # seconds
      intervention:
        auto_continue: true
        max_retries: 3
        recovery_strategies: ["prompt", "restart", "escalate"]
      batch:
        supported_formats: ["json", "yaml", "txt"]
        max_script_size: 1048576  # 1MB
        execution_timeout: 3600   # 1 hour
        auto_continue: true
        error_handling: "continue_on_error"
    continuation_config:
      rules:
        - trigger_tools: ["session_inspector", "log_analyzer"]
          keywords: ["stall", "stuck", "waiting", "timeout", "not responding"]
          continuation_message: "Based on the analysis, I'll now attempt to resolve the issue. Let me inject a continuation prompt to unstick the agent."
        - trigger_tools: ["python_executor"]
          keywords: ["analyze", "debug", "investigate", "examine"]
          continuation_message: "I've executed the debugging script. Let me analyze the results and provide recommendations."
        - trigger_tools: ["script_parser"]
          keywords: ["parse", "read", "load", "process"]
          continuation_message: "I've parsed the script. Now let me execute the commands in sequence."
        - trigger_tools: ["batch_command"]
          keywords: ["execute", "run", "process", "command"]
          continuation_message: "Command executed. Proceeding to the next command in the script."
        - trigger_tools: ["session_health"]
          keywords: ["health", "status", "check", "monitor"]
          continuation_message: "I've checked the session health. Let me analyze the results and provide insights."
        - trigger_tools: ["session_analysis"]
          keywords: ["analyze", "investigate", "diagnose", "troubleshoot"]
          continuation_message: "Based on my analysis, here are my findings and recommendations."
        - trigger_tools: ["monitoring_control"]
          keywords: ["enable", "disable", "configure", "adjust", "threshold"]
          continuation_message: "Monitoring settings have been updated. The changes are now active."
      default_message: "Continue with the current task."