
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
      shell: bash
    - name: Set PYTHONPATH for PowerShell
      run: |
        echo "PYTHONPATH=$env:PYTHONPATH;$(pwd)\src" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh
    - name: Create venv for powershell test
      run: |
        python -m venv .venv
        .venv\Scripts\pip install -r requirements.txt
      shell: pwsh 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
    - name: Install dependencies for PowerShell
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
      shell: pwsh
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: pytest
    - name: Summarize performance metrics
      run: python project_dev/summarize_performance_metrics.py
      shell: pwsh
    - name: Run interactive client script tests
      run: pytest tests/interactive_server/test_interactive_client_script.py
      shell: pwsh
