name: Tool Regression Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'ai_whisperer/tools/**'
      - 'ai_whisperer/services/execution/**'
      - 'interactive_server/**'
      - 'scripts/conversations/test_*.txt'
      - '.github/workflows/tool-regression-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ai_whisperer/tools/**'
      - 'ai_whisperer/services/execution/**'
      - 'interactive_server/**'
      - '.github/workflows/tool-regression-tests.yml'

jobs:
  tool-regression:
    runs-on: ubuntu-latest
    # Skip this job in CI as it requires real API keys
    if: false
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Setup test config
      run: |
        # Create a minimal test config for CI
        cat > config/main.yaml << EOF
        openrouter:
          model: mock/test-model
          params:
            temperature: 0.7
            max_tokens: 100
        prompts: {}
        workspace_ignore_patterns:
        - .git
        - .venv
        - __pycache__
        EOF
        # Use a test API key for CI
        echo "OPENROUTER_API_KEY=test-key-ci" >> $GITHUB_ENV
    
    - name: Run tool regression tests
      run: |
        python scripts/run_tool_regression_tests.py
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: tool-regression-results
        path: test_results/